import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "./context/LoadingContext";
import LoadingOverlay from "./components/LoadingOverlay";
import { ToastProvider } from "./context/ToastContext";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["400", "500", "700"], // ใส่น้ำหนักที่ต้องใช้
  display: "swap",
  variable: "--font-thai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={kanit.className}>
      <body>
        <ToastProvider>
          <LoadingProvider>
            <LoadingOverlay />
            {children}
          </LoadingProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
